stages:
  - version
  - test
  - build
  - security-scan
  - release
  - deploy

include:
  # Run Unit test on the source code 
  - project: 'pms/infra/ci-cd-config'
    ref: main
    file: '/dotnet-unit-test.yml'

  # Run SonarQube Check on the source code 
  - project: 'pms/infra/ci-cd-config'
    ref: main
    file: '/sonarqube-dotnet.yml'

  # Building docker image 
  - project: 'pms/infra/ci-cd-config'
    ref: main
    file: '/build-docker-to-acr.yml'
    
  # Container sec docker image 
  - project: 'pms/infra/ci-cd-config'
    ref: main
    file: '/container-sec-scan.yml'

  # Tag and creating release
  - project: 'pms/infra/ci-cd-config'
    ref: main
    file: '/tag-and-release.yml'
    
  # # Deployment to Azure kubernetes service
  # - project: 'identityserver/infra/cicd-configs'
  #   ref: main
  #   file: '/.gitlab-ci-template-deploy-aks.yml'

  # Update the helm manifest file with the new build
  - project: 'pms/infra/ci-cd-config'
    ref: main
    file: '/update-helm.yml'
